#!/bin/bash

bspc config border_width   2
bspc config window_gap     5
bspc config top_padding   30
bspc config split_ratio    0.52

bspc config single_monocle     true
bspc config gapless_monocle    true
bspc config borderless_monocle true

bspc config click_to_focus        true
bspc config focus_follows_pointer true

bspc config pointer_modifier mod1
bspc config pointer_action1  move
bspc config pointer_action2  resize_side
bspc config pointer_action3  resize_corner

bspc config normal_border_color   '#191b21'
bspc config active_border_color   '#191b21'
bspc config focused_border_color  '#dcdfe3'
bspc config presel_feedback_color '#4dadd4'

bspc monitor -d home terminal code browser files videos other mail chat music

bspc rule -a mpv desktop=videos
bspc rule -a Firefox desktop=browser
bspc rule -a Nautilus desktop=files
bspc rule -a URxvt:mutt desktop=mail
bspc rule -a URxvt:ncmpcpp desktop=music
bspc rule -a URxvt:tmux desktop=terminal

# run polybar
polybar panel &

urxvt -name mutt &
urxvt -name ncmpcpp &
urxvt -name tmux -e tmux &
