#!/bin/bash
#
# ~/.xsessionrc
#
# executed by gdm

# update x resources db
xrdb ~/.Xresources
# disable x beep
xset -b
# disable x screen saver
xset s off
# disable x display power management signaling
#xset -dpms
