#!/bin/bash

bspc config border_width   2
bspc config window_gap     5
bspc config top_padding   30
bspc config split_ratio    0.5

bspc config single_monocle     true
bspc config gapless_monocle    true
bspc config borderless_monocle true

bspc config focus_follows_pointer true

bspc config pointer_modifier mod1
bspc config pointer_action1  move
bspc config pointer_action2  resize_side
bspc config pointer_action3  resize_corner

bspc config normal_border_color   '#191b21'
bspc config active_border_color   '#191b21'
bspc config focused_border_color  '#d3dae3'
bspc config presel_feedback_color '#1f62b0'

bspc monitor -d home terminal code browser files videos other mail chat music

bspc config external_rules_command "$(which external_rules)"

# run polybar
polybar panel &

alacritty --class Alacritty,mail &
alacritty --class Alacritty,music &
alacritty --class Alacritty,terminal -e tmux &
